curl 'https://api1.passportindia.gov.in/v1/secure/bookappointonline' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H "Authorization: Bearer $(cat "$(dirname "$0")/bearer_token.txt")" \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: https://services1.passportindia.gov.in' \
  -H 'Referer: https://services1.passportindia.gov.in/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="149", "Chromium";v="149", "Not)A;Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'x-aim-plugin-installed: true' \
  --data-raw '{"requestResponseMap":{"appRefNo":"25-0054608322","enquiryQuota":"","appTask":"Schedule","appointmentQuota":"Online","calendarDisplayFlag":"N","calApptDate":"28/08/2026","pboId":"6"}}'
