curl 'https://api1.passportindia.gov.in/v1/secure/createappointonline' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJRRUVSMTExMDIwMjIiLCJhdWQiOiJPbmxpbmUtQ2l0aXplbi1BcGkiLCJuYmYiOjE3ODA3NTYxMTksImlzcyI6Imh0dHBzOi8vd3d3LnBhc3Nwb3J0aW5kaWEuZ292LmluL3BzcCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4iLCJleHAiOjE3ODA3NzA1MTksImlhdCI6MTc4MDc1NjExOSwianRpIjoiMTA5Mzg1NzEyNTE5NTE1NCJ9.ZRxhw0ud9YiOVQSCohLlPZ385pGmc3ytNNDPlL2Mk1FdMkOmDn9BGimG7n5OLuRdTObVFfveO5Yb9A24LhAdPIaVCFKOEEPZOSRpsf2Bdnu3YX_KuICUS6cj2eFKCFHgUiIPQwnL_uKUPS_qO9ocLB5c4vurtHWeLDm1uxpUKk7ZPz1j_WfISD_BZqslx9unbkpXmj7GcgoEGZKiNO-2oe33nZJWl9hn2ee2WtZDar-e8AC1hoaF4_4iQGKw0bShpsRNBlxBp3uwHy80BBZz0jT8PYVuKSLahYZuyfw0S4IseZ3-h5yLI89LlnVcpzW3o_varHOSNzWEqVihbubGQA' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: https://services1.passportindia.gov.in' \
  -H 'Referer: https://services1.passportindia.gov.in/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="149", "Chromium";v="149", "Not)A;Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'x-aim-plugin-installed: true' \
  --data-raw '{"requestResponseMap":{"appRefNo":"26-0065298114","enquiryQuota":"","isGOESFlag":"N","appTask":"Schedule","schemeId":342,"pboId":"6"}}'